apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
spec:
  selector:
    matchLabels:
      app: pingpong
  replicas: 3
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: bretfisher/pingpong:latest
