name: Build and Push Facepalm Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'facepalm/**'
      - '.github/workflows/facepalm.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'facepalm/**'
      - '.github/workflows/facepalm.yaml'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 12 15 * *'
  workflow_dispatch:
    # run whenever we want!

jobs:
  call-docker-workflow:
    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    uses: bretfisher/github-actions-templates/.github/workflows/docker-build-and-push.yaml@main
    with:
      image-names: |
          bretfisher/facepalm
          ghcr.io/bretfisher/facepalm
      context: facepalm
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
