name: build-and-push-hub-images

on:
  push:
    branches: master

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push clock
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./clock.Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            bretfisher/clock:latest
      -
        name: Build and push date
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./date.Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            bretfisher/date:latest
      -
        name: Build and push facepalm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./facepalm.Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            bretfisher/facepalm:latest
      -
        name: Build and push pingpong
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pingpong.Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            bretfisher/pingpong:latest
      -
        name: Build and push top
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./top.Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            bretfisher/top:latest
